ALTER TABLE TBL032_MOVTO_INV ADD CODIGO_AREA VARCHAR(10)  NULL
GO

UPDATE TBL032_MOVTO_INV 
SET TBL032_MOVTO_INV.CODIGO_AREA = PRODUCTO.CODIGO_AREA
FROM TBL032_MOVTO_INV  
INNER JOIN TBL007_PRODUCTO PRODUCTO
ON TBL032_MOVTO_INV.CODIGO_PRODUCTO = PRODUCTO.CODIGO_PRODUCTO


ALTER TABLE TBL032_MOVTO_INV ADD FOREIGN KEY (CODIGO_AREA) REFERENCES TBL005_AREA(CODIGO_AREA) 
